export const CHANGE_MOBILE_MODE = "CHANGE_MOBILE_MODE";

export const START_CHECK_ONLINE = "START_CHECK_ONLINE";
export const SET_ONLINE_CLIENT_STATUS = "SET_ONLINE_CLIENT_STATUS";
export const SET_OFFLINE_CLIENT_STATUS = "SET_OFFLINE_CLIENT_STATUS";
